kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ns.yaml
  - proxy

images:
  # workspace-manager
  - name: quay.io/konflux-ci/workspace-manager
    digest: sha256:8ab7aec8770e70dfdda2a381fc06b933e2428f110b9358c6f88a07d00458935a
  - name: quay.io/konflux-ci/konflux-ui
    digest: sha256:92fe9797bd7010b904c0524b97a0dfe428d68e5290de1eb5ec7c634fc2157199

namespace: konflux-ui
