kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ns.yaml
  - proxy

images:
  # workspace-manager
  - name: quay.io/konflux-ci/workspace-manager
    digest: sha256:8ab7aec8770e70dfdda2a381fc06b933e2428f110b9358c6f88a07d00458935a
  - name: quay.io/konflux-ci/konflux-ui
    digest: sha256:5554af2108b557bd686e3c6c47d59ed87305f6003f819451246740b76af1683c

namespace: konflux-ui
